--- #YAML:1.0
name:                Kvasir
version:             0.03
abstract:            Generic rule based processing engine
license:             MIT
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    List::Util:                    0
    Object::Tiny:                  0
    Scalar::Util:                  0
    Test::AbstractMethod:          0
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Claes Jakobsson <claesjac@cpan.org>
